//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhanMemBanHang.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDon
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HoaDon()
        {
            this.ChiTietHoaDon = new HashSet<ChiTietHoaDon>();
        }
    
        public int MaHD { get; set; }
        public System.DateTime NgayLap { get; set; }
        public int MaNV { get; set; }
        public int MaPager { get; set; }
        public int MaKH { get; set; }
        public decimal TongTien { get; set; }
        public decimal ThanhTien { get; set; }
        public string TrangThai { get; set; }
        public string PhuongThucTT { get; set; }
        public System.DateTime ThoiGianGoi { get; set; }
        public string LoaiDon { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietHoaDon> ChiTietHoaDon { get; set; }
        public virtual KhachHang KhachHang { get; set; }
        public virtual Pager Pager { get; set; }
        public virtual NhanVien NhanVien { get; set; }
    }
}
