//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhanMemBanHang.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pager
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pager()
        {
            this.HoaDon = new HashSet<HoaDon>();
        }
    
        public int MaPager { get; set; }
        public string TenPager { get; set; }
        public string GhiChu { get; set; }
        public string TrangThai { get; set; }
        public int SoLanSuDung { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HoaDon> HoaDon { get; set; }
    }
}
